{'gmtUpdated': 1623737335,
 'calendar': {'seasonID': 82,
  'leagueID': '7',
  'seasonName': '2020-21',
  'fullName': 'UEFA Europa League (Europe) 2020-21',
  'stages': False,
  'matchdays': [{'matchdayID': '2074',
    'matchdayName': 'MatchDay 1',
    'matchdayPlayoff': '0',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '19280',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '53'},
      'homeParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '6'},
      'awayParticipant': {'participantID': '64',
       'participantName': 'OGC Nice',
       'score': '2'}},
     {'matchID': '19281',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '571'},
      'homeParticipant': {'participantID': '576',
       'participantName': 'PFC CSKA Sofia',
       'score': '0'},
      'awayParticipant': {'participantID': '154',
       'participantName': 'CFR Cluj',
       'score': '2'}},
     {'matchID': '19282',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '698'},
      'homeParticipant': {'participantID': '715',
       'participantName': 'Dundalk FC',
       'score': '1'},
      'awayParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '2'}},
     {'matchID': '19283',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '701'},
      'homeParticipant': {'participantID': '718',
       'participantName': "Hapoel Be'er Sheva FC",
       'score': '3'},
      'awayParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '1'}},
     {'matchID': '19284',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '704'},
      'homeParticipant': {'participantID': '723',
       'participantName': 'Lech Poznań',
       'score': '2'},
      'awayParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '4'}},
     {'matchID': '19285',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '121'},
      'homeParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '0'},
      'awayParticipant': {'participantID': '173',
       'participantName': 'AZ Alkmaar',
       'score': '1'}},
     {'matchID': '19286',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '270'},
      'homeParticipant': {'participantID': '240',
       'participantName': 'PAOK FC',
       'score': '1'},
      'awayParticipant': {'participantID': '722',
       'participantName': 'AC Omonia Nicosia',
       'score': '1'}},
     {'matchID': '19287',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '187'},
      'homeParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '1'},
      'awayParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '2'}},
     {'matchID': '19288',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '699'},
      'homeParticipant': {'participantID': '716',
       'participantName': 'SK Rapid Wien',
       'score': '1'},
      'awayParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '2'}},
     {'matchID': '19289',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '703'},
      'homeParticipant': {'participantID': '721',
       'participantName': 'HNK Rijeka',
       'score': '0'},
      'awayParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '1'}},
     {'matchID': '19290',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '191'},
      'homeParticipant': {'participantID': '155',
       'participantName': 'R Standard Liège',
       'score': '0'},
      'awayParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '2'}},
     {'matchID': '19291',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '16:55',
      'matchVenue': {'venueID': '194'},
      'homeParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '1'},
      'awayParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '2'}},
     {'matchID': '19292',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '203'},
      'homeParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '3'},
      'awayParticipant': {'participantID': '230',
       'participantName': 'AEK Athens FC',
       'score': '0'}},
     {'matchID': '19293',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '190'},
      'homeParticipant': {'participantID': '153',
       'participantName': 'Celtic FC',
       'score': '1'},
      'awayParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '3'}},
     {'matchID': '19294',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '168'},
      'homeParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '0'},
      'awayParticipant': {'participantID': '159',
       'participantName': 'Feyenoord Rotterdam',
       'score': '0'}},
     {'matchID': '19295',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '50'},
      'homeParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '2'},
      'awayParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '0'}},
     {'matchID': '19296',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '1'},
      'homeParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '3'},
      'awayParticipant': {'participantID': '418',
       'participantName': 'FC Zorya Luhansk',
       'score': '0'}},
     {'matchID': '19297',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '646'},
      'homeParticipant': {'participantID': '685',
       'participantName': 'FC Slovan Liberec',
       'score': '1'},
      'awayParticipant': {'participantID': '164',
       'participantName': 'KAA Gent',
       'score': '0'}},
     {'matchID': '19298',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '199'},
      'homeParticipant': {'participantID': '162',
       'participantName': 'PFC Ludogorets Razgrad',
       'score': '1'},
      'awayParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '2'}},
     {'matchID': '19299',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '702'},
      'homeParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '1'},
      'awayParticipant': {'participantID': '140',
       'participantName': 'Qarabağ FK',
       'score': '0'}},
     {'matchID': '19300',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '655'},
      'homeParticipant': {'participantID': '682',
       'participantName': 'AC Sparta Praha',
       'score': '1'},
      'awayParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '4'}},
     {'matchID': '19301',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '23'},
      'homeParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '3'},
      'awayParticipant': {'participantID': '152',
       'participantName': 'LASK Linz',
       'score': '0'}},
     {'matchID': '19302',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '5'},
      'awayParticipant': {'participantID': '502',
       'participantName': 'Sivasspor',
       'score': '3'}},
     {'matchID': '19418',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-22',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '206'},
      'homeParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '1'},
      'awayParticipant': {'participantID': '161',
       'participantName': 'PFC CSKA Moscow',
       'score': '1'}}]},
   {'matchdayID': '2075',
    'matchdayName': 'MatchDay 2',
    'matchdayPlayoff': '0',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '19303',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '126'},
      'homeParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '3'},
      'awayParticipant': {'participantID': '682',
       'participantName': 'AC Sparta Praha',
       'score': '0'}},
     {'matchID': '19304',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '267'},
      'homeParticipant': {'participantID': '230',
       'participantName': 'AEK Athens FC',
       'score': '1'},
      'awayParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '2'}},
     {'matchID': '19305',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '504'},
      'homeParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '1'},
      'awayParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '0'}},
     {'matchID': '19306',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '197'},
      'homeParticipant': {'participantID': '161',
       'participantName': 'PFC CSKA Moscow',
       'score': '0'},
      'awayParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '0'}},
     {'matchID': '19307',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '165'},
      'homeParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '5'},
      'awayParticipant': {'participantID': '685',
       'participantName': 'FC Slovan Liberec',
       'score': '1'}},
     {'matchID': '19308',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '434'},
      'homeParticipant': {'participantID': '418',
       'participantName': 'FC Zorya Luhansk',
       'score': '1'},
      'awayParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '2'}},
     {'matchID': '19309',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '209'},
      'homeParticipant': {'participantID': '164',
       'participantName': 'KAA Gent',
       'score': '1'},
      'awayParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '4'}},
     {'matchID': '19310',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '185'},
      'homeParticipant': {'participantID': '152',
       'participantName': 'LASK Linz',
       'score': '4'},
      'awayParticipant': {'participantID': '162',
       'participantName': 'PFC Ludogorets Razgrad',
       'score': '3'}},
     {'matchID': '19311',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '68'},
      'homeParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '2'},
      'awayParticipant': {'participantID': '153',
       'participantName': 'Celtic FC',
       'score': '2'}},
     {'matchID': '19312',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '176'},
      'homeParticipant': {'participantID': '140',
       'participantName': 'Qarabağ FK',
       'score': '1'},
      'awayParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '3'}},
     {'matchID': '19313',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '526'},
      'homeParticipant': {'participantID': '502',
       'participantName': 'Sivasspor',
       'score': '1'},
      'awayParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '2'}},
     {'matchID': '19419',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '195'},
      'homeParticipant': {'participantID': '159',
       'participantName': 'Feyenoord Rotterdam',
       'score': '1'},
      'awayParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '4'}},
     {'matchID': '19314',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '10'},
      'homeParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '3'},
      'awayParticipant': {'participantID': '715',
       'participantName': 'Dundalk FC',
       'score': '0'}},
     {'matchID': '19315',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '128'},
      'homeParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '0'},
      'awayParticipant': {'participantID': '576',
       'participantName': 'PFC CSKA Sofia',
       'score': '0'}},
     {'matchID': '19316',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '200'},
      'homeParticipant': {'participantID': '173',
       'participantName': 'AZ Alkmaar',
       'score': '4'},
      'awayParticipant': {'participantID': '721',
       'participantName': 'HNK Rijeka',
       'score': '1'}},
     {'matchID': '19317',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '162'},
      'homeParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '3'},
      'awayParticipant': {'participantID': '155',
       'participantName': 'R Standard Liège',
       'score': '0'}},
     {'matchID': '19318',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '189'},
      'homeParticipant': {'participantID': '154',
       'participantName': 'CFR Cluj',
       'score': '1'},
      'awayParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '1'}},
     {'matchID': '19319',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '143'},
      'homeParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '0'},
      'awayParticipant': {'participantID': '240',
       'participantName': 'PAOK FC',
       'score': '0'}},
     {'matchID': '19320',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '700'},
      'homeParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '1'},
      'awayParticipant': {'participantID': '716',
       'participantName': 'SK Rapid Wien',
       'score': '0'}},
     {'matchID': '19321',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '63'},
      'homeParticipant': {'participantID': '64',
       'participantName': 'OGC Nice',
       'score': '1'},
      'awayParticipant': {'participantID': '718',
       'participantName': "Hapoel Be'er Sheva FC",
       'score': '0'}},
     {'matchID': '19322',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '175'},
      'homeParticipant': {'participantID': '722',
       'participantName': 'AC Omonia Nicosia',
       'score': '1'},
      'awayParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '2'}},
     {'matchID': '19323',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '196'},
      'homeParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '1'},
      'awayParticipant': {'participantID': '723',
       'participantName': 'Lech Poznań',
       'score': '0'}},
     {'matchID': '19324',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '26'},
      'homeParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '0'},
      'awayParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '1'}},
     {'matchID': '19325',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-10-29',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '171'},
      'homeParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '1'},
      'awayParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '0'}}]},
   {'matchdayID': '2076',
    'matchdayName': 'MatchDay 3',
    'matchdayPlayoff': '0',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '19326',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '128'},
      'homeParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '5'},
      'awayParticipant': {'participantID': '154',
       'participantName': 'CFR Cluj',
       'score': '0'}},
     {'matchID': '19327',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '162'},
      'homeParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '3'},
      'awayParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '3'}},
     {'matchID': '19328',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '701'},
      'homeParticipant': {'participantID': '718',
       'participantName': "Hapoel Be'er Sheva FC",
       'score': '2'},
      'awayParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '4'}},
     {'matchID': '19329',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '704'},
      'homeParticipant': {'participantID': '723',
       'participantName': 'Lech Poznań',
       'score': '3'},
      'awayParticipant': {'participantID': '155',
       'participantName': 'R Standard Liège',
       'score': '1'}},
     {'matchID': '19330',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '199'},
      'homeParticipant': {'participantID': '162',
       'participantName': 'PFC Ludogorets Razgrad',
       'score': '1'},
      'awayParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '3'}},
     {'matchID': '19331',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '175'},
      'homeParticipant': {'participantID': '722',
       'participantName': 'AC Omonia Nicosia',
       'score': '0'},
      'awayParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '2'}},
     {'matchID': '19332',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '270'},
      'homeParticipant': {'participantID': '240',
       'participantName': 'PAOK FC',
       'score': '4'},
      'awayParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '1'}},
     {'matchID': '19333',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '699'},
      'homeParticipant': {'participantID': '716',
       'participantName': 'SK Rapid Wien',
       'score': '4'},
      'awayParticipant': {'participantID': '715',
       'participantName': 'Dundalk FC',
       'score': '3'}},
     {'matchID': '19334',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '26'},
      'homeParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '1'},
      'awayParticipant': {'participantID': '173',
       'participantName': 'AZ Alkmaar',
       'score': '0'}},
     {'matchID': '19335',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '703'},
      'homeParticipant': {'participantID': '721',
       'participantName': 'HNK Rijeka',
       'score': '1'},
      'awayParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '2'}},
     {'matchID': '19336',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '526'},
      'homeParticipant': {'participantID': '502',
       'participantName': 'Sivasspor',
       'score': '2'},
      'awayParticipant': {'participantID': '140',
       'participantName': 'Qarabağ FK',
       'score': '0'}},
     {'matchID': '19337',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '171'},
      'homeParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '3'},
      'awayParticipant': {'participantID': '64',
       'participantName': 'OGC Nice',
       'score': '2'}},
     {'matchID': '19338',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '126'},
      'homeParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '0'},
      'awayParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '3'}},
     {'matchID': '19339',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '504'},
      'homeParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '0'},
      'awayParticipant': {'participantID': '152',
       'participantName': 'LASK Linz',
       'score': '1'}},
     {'matchID': '19340',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '10'},
      'homeParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '4'},
      'awayParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '1'}},
     {'matchID': '19341',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '190'},
      'homeParticipant': {'participantID': '153',
       'participantName': 'Celtic FC',
       'score': '1'},
      'awayParticipant': {'participantID': '682',
       'participantName': 'AC Sparta Praha',
       'score': '4'}},
     {'matchID': '19342',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '195'},
      'homeParticipant': {'participantID': '159',
       'participantName': 'Feyenoord Rotterdam',
       'score': '3'},
      'awayParticipant': {'participantID': '161',
       'participantName': 'PFC CSKA Moscow',
       'score': '1'}},
     {'matchID': '19343',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '165'},
      'homeParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '2'},
      'awayParticipant': {'participantID': '164',
       'participantName': 'KAA Gent',
       'score': '1'}},
     {'matchID': '19344',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '434'},
      'homeParticipant': {'participantID': '418',
       'participantName': 'FC Zorya Luhansk',
       'score': '1'},
      'awayParticipant': {'participantID': '230',
       'participantName': 'AEK Athens FC',
       'score': '4'}},
     {'matchID': '19345',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '50'},
      'homeParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '5'},
      'awayParticipant': {'participantID': '685',
       'participantName': 'FC Slovan Liberec',
       'score': '0'}},
     {'matchID': '19346',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '1'},
      'homeParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '4'},
      'awayParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '0'}},
     {'matchID': '19347',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '4'},
      'awayParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '0'}},
     {'matchID': '19348',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '194'},
      'homeParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '3'},
      'awayParticipant': {'participantID': '576',
       'participantName': 'PFC CSKA Sofia',
       'score': '0'}},
     {'matchID': '19420',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-05',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '168'},
      'homeParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '1'},
      'awayParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '0'}}]},
   {'matchdayID': '2077',
    'matchdayName': 'MatchDay 4',
    'matchdayPlayoff': '0',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '19349',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '267'},
      'homeParticipant': {'participantID': '230',
       'participantName': 'AEK Athens FC',
       'score': '0'},
      'awayParticipant': {'participantID': '418',
       'participantName': 'FC Zorya Luhansk',
       'score': '3'}},
     {'matchID': '19350',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '203'},
      'homeParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '3'},
      'awayParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '3'}},
     {'matchID': '19351',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '197'},
      'homeParticipant': {'participantID': '161',
       'participantName': 'PFC CSKA Moscow',
       'score': '0'},
      'awayParticipant': {'participantID': '159',
       'participantName': 'Feyenoord Rotterdam',
       'score': '0'}},
     {'matchID': '19352',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '571'},
      'homeParticipant': {'participantID': '576',
       'participantName': 'PFC CSKA Sofia',
       'score': '0'},
      'awayParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '1'}},
     {'matchID': '19353',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '209'},
      'homeParticipant': {'participantID': '164',
       'participantName': 'KAA Gent',
       'score': '0'},
      'awayParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '2'}},
     {'matchID': '19354',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '185'},
      'homeParticipant': {'participantID': '152',
       'participantName': 'LASK Linz',
       'score': '0'},
      'awayParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '2'}},
     {'matchID': '19355',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '646'},
      'homeParticipant': {'participantID': '685',
       'participantName': 'FC Slovan Liberec',
       'score': '0'},
      'awayParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '2'}},
     {'matchID': '19356',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '68'},
      'homeParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '1'},
      'awayParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '1'}},
     {'matchID': '19357',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '702'},
      'homeParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '1'},
      'awayParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '1'}},
     {'matchID': '19358',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '700'},
      'homeParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '0'},
      'awayParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '3'}},
     {'matchID': '19359',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '176'},
      'homeParticipant': {'participantID': '140',
       'participantName': 'Qarabağ FK',
       'score': '2'},
      'awayParticipant': {'participantID': '502',
       'participantName': 'Sivasspor',
       'score': '3'}},
     {'matchID': '19360',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '655'},
      'homeParticipant': {'participantID': '682',
       'participantName': 'AC Sparta Praha',
       'score': '4'},
      'awayParticipant': {'participantID': '153',
       'participantName': 'Celtic FC',
       'score': '1'}},
     {'matchID': '19421',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '206'},
      'homeParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '0'},
      'awayParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '3'}},
     {'matchID': '19361',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '200'},
      'homeParticipant': {'participantID': '173',
       'participantName': 'AZ Alkmaar',
       'score': '0'},
      'awayParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '0'}},
     {'matchID': '19362',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '53'},
      'homeParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '4'},
      'awayParticipant': {'participantID': '718',
       'participantName': "Hapoel Be'er Sheva FC",
       'score': '1'}},
     {'matchID': '19363',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '189'},
      'homeParticipant': {'participantID': '154',
       'participantName': 'CFR Cluj',
       'score': '0'},
      'awayParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '2'}},
     {'matchID': '19364',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '698'},
      'homeParticipant': {'participantID': '715',
       'participantName': 'Dundalk FC',
       'score': '1'},
      'awayParticipant': {'participantID': '716',
       'participantName': 'SK Rapid Wien',
       'score': '3'}},
     {'matchID': '19365',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '143'},
      'homeParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '2'},
      'awayParticipant': {'participantID': '722',
       'participantName': 'AC Omonia Nicosia',
       'score': '1'}},
     {'matchID': '19366',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '121'},
      'homeParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '2'},
      'awayParticipant': {'participantID': '721',
       'participantName': 'HNK Rijeka',
       'score': '0'}},
     {'matchID': '19367',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '63'},
      'homeParticipant': {'participantID': '64',
       'participantName': 'OGC Nice',
       'score': '1'},
      'awayParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '3'}},
     {'matchID': '19368',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '187'},
      'homeParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '3'},
      'awayParticipant': {'participantID': '240',
       'participantName': 'PAOK FC',
       'score': '2'}},
     {'matchID': '19369',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '196'},
      'homeParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '2'},
      'awayParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '2'}},
     {'matchID': '19370',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '191'},
      'homeParticipant': {'participantID': '155',
       'participantName': 'R Standard Liège',
       'score': '2'},
      'awayParticipant': {'participantID': '723',
       'participantName': 'Lech Poznań',
       'score': '1'}},
     {'matchID': '19371',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-11-26',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '23'},
      'homeParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '4'},
      'awayParticipant': {'participantID': '162',
       'participantName': 'PFC Ludogorets Razgrad',
       'score': '0'}}]},
   {'matchdayID': '2078',
    'matchdayName': 'MatchDay 5',
    'matchdayPlayoff': '0',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '19372',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '126'},
      'homeParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '4'},
      'awayParticipant': {'participantID': '153',
       'participantName': 'Celtic FC',
       'score': '2'}},
     {'matchID': '19373',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '267'},
      'homeParticipant': {'participantID': '230',
       'participantName': 'AEK Athens FC',
       'score': '2'},
      'awayParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '4'}},
     {'matchID': '19374',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '504'},
      'homeParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '3'},
      'awayParticipant': {'participantID': '162',
       'participantName': 'PFC Ludogorets Razgrad',
       'score': '1'}},
     {'matchID': '19375',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '195'},
      'homeParticipant': {'participantID': '159',
       'participantName': 'Feyenoord Rotterdam',
       'score': '0'},
      'awayParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '2'}},
     {'matchID': '19376',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '165'},
      'homeParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '0'},
      'awayParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '0'}},
     {'matchID': '19377',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '434'},
      'homeParticipant': {'participantID': '418',
       'participantName': 'FC Zorya Luhansk',
       'score': '1'},
      'awayParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '0'}},
     {'matchID': '19378',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '209'},
      'homeParticipant': {'participantID': '164',
       'participantName': 'KAA Gent',
       'score': '1'},
      'awayParticipant': {'participantID': '685',
       'participantName': 'FC Slovan Liberec',
       'score': '2'}},
     {'matchID': '19379',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '185'},
      'homeParticipant': {'participantID': '152',
       'participantName': 'LASK Linz',
       'score': '3'},
      'awayParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '3'}},
     {'matchID': '19380',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '68'},
      'homeParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '2'},
      'awayParticipant': {'participantID': '682',
       'participantName': 'AC Sparta Praha',
       'score': '1'}},
     {'matchID': '19381',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '176'},
      'homeParticipant': {'participantID': '140',
       'participantName': 'Qarabağ FK',
       'score': '1'},
      'awayParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '1'}},
     {'matchID': '19382',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '526'},
      'homeParticipant': {'participantID': '502',
       'participantName': 'Sivasspor',
       'score': '0'},
      'awayParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '1'}},
     {'matchID': '19422',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '197'},
      'homeParticipant': {'participantID': '161',
       'participantName': 'PFC CSKA Moscow',
       'score': '0'},
      'awayParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '1'}},
     {'matchID': '19383',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '10'},
      'homeParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '4'},
      'awayParticipant': {'participantID': '716',
       'participantName': 'SK Rapid Wien',
       'score': '1'}},
     {'matchID': '19384',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '128'},
      'homeParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '3'},
      'awayParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '1'}},
     {'matchID': '19385',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '200'},
      'homeParticipant': {'participantID': '173',
       'participantName': 'AZ Alkmaar',
       'score': '1'},
      'awayParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '1'}},
     {'matchID': '19386',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '162'},
      'homeParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '4'},
      'awayParticipant': {'participantID': '723',
       'participantName': 'Lech Poznań',
       'score': '0'}},
     {'matchID': '19387',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '189'},
      'homeParticipant': {'participantID': '154',
       'participantName': 'CFR Cluj',
       'score': '0'},
      'awayParticipant': {'participantID': '576',
       'participantName': 'PFC CSKA Sofia',
       'score': '0'}},
     {'matchID': '19388',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '143'},
      'homeParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '0'},
      'awayParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '1'}},
     {'matchID': '19389',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '700'},
      'homeParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '3'},
      'awayParticipant': {'participantID': '715',
       'participantName': 'Dundalk FC',
       'score': '1'}},
     {'matchID': '19390',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '63'},
      'homeParticipant': {'participantID': '64',
       'participantName': 'OGC Nice',
       'score': '2'},
      'awayParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '3'}},
     {'matchID': '19391',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '175'},
      'homeParticipant': {'participantID': '722',
       'participantName': 'AC Omonia Nicosia',
       'score': '2'},
      'awayParticipant': {'participantID': '240',
       'participantName': 'PAOK FC',
       'score': '1'}},
     {'matchID': '19392',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '196'},
      'homeParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '3'},
      'awayParticipant': {'participantID': '155',
       'participantName': 'R Standard Liège',
       'score': '2'}},
     {'matchID': '19393',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '26'},
      'homeParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '2'},
      'awayParticipant': {'participantID': '721',
       'participantName': 'HNK Rijeka',
       'score': '2'}},
     {'matchID': '19394',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-03',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '171'},
      'homeParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '3'},
      'awayParticipant': {'participantID': '718',
       'participantName': "Hapoel Be'er Sheva FC",
       'score': '0'}}]},
   {'matchdayID': '2079',
    'matchdayName': 'MatchDay 6',
    'matchdayPlayoff': '0',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '19395',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '53'},
      'homeParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '4'},
      'awayParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '0'}},
     {'matchID': '19396',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '571'},
      'homeParticipant': {'participantID': '576',
       'participantName': 'PFC CSKA Sofia',
       'score': '3'},
      'awayParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '1'}},
     {'matchID': '19397',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '698'},
      'homeParticipant': {'participantID': '715',
       'participantName': 'Dundalk FC',
       'score': '2'},
      'awayParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '4'}},
     {'matchID': '19398',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '701'},
      'homeParticipant': {'participantID': '718',
       'participantName': "Hapoel Be'er Sheva FC",
       'score': '1'},
      'awayParticipant': {'participantID': '64',
       'participantName': 'OGC Nice',
       'score': '0'}},
     {'matchID': '19399',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '704'},
      'homeParticipant': {'participantID': '723',
       'participantName': 'Lech Poznań',
       'score': '0'},
      'awayParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '2'}},
     {'matchID': '19400',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '121'},
      'homeParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '1'},
      'awayParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '1'}},
     {'matchID': '19401',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '270'},
      'homeParticipant': {'participantID': '240',
       'participantName': 'PAOK FC',
       'score': '0'},
      'awayParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '0'}},
     {'matchID': '19402',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '187'},
      'homeParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '4'},
      'awayParticipant': {'participantID': '722',
       'participantName': 'AC Omonia Nicosia',
       'score': '0'}},
     {'matchID': '19403',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '699'},
      'homeParticipant': {'participantID': '716',
       'participantName': 'SK Rapid Wien',
       'score': '2'},
      'awayParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '2'}},
     {'matchID': '19404',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '703'},
      'homeParticipant': {'participantID': '721',
       'participantName': 'HNK Rijeka',
       'score': '2'},
      'awayParticipant': {'participantID': '173',
       'participantName': 'AZ Alkmaar',
       'score': '1'}},
     {'matchID': '19405',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '191'},
      'homeParticipant': {'participantID': '155',
       'participantName': 'R Standard Liège',
       'score': '2'},
      'awayParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '2'}},
     {'matchID': '19406',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '194'},
      'homeParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '2'},
      'awayParticipant': {'participantID': '154',
       'participantName': 'CFR Cluj',
       'score': '1'}},
     {'matchID': '19407',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '203'},
      'homeParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '2'},
      'awayParticipant': {'participantID': '418',
       'participantName': 'FC Zorya Luhansk',
       'score': '0'}},
     {'matchID': '19408',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '190'},
      'homeParticipant': {'participantID': '153',
       'participantName': 'Celtic FC',
       'score': '3'},
      'awayParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '2'}},
     {'matchID': '19409',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '168'},
      'homeParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '3'},
      'awayParticipant': {'participantID': '161',
       'participantName': 'PFC CSKA Moscow',
       'score': '1'}},
     {'matchID': '19410',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '50'},
      'homeParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '4'},
      'awayParticipant': {'participantID': '164',
       'participantName': 'KAA Gent',
       'score': '1'}},
     {'matchID': '19411',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '1'},
      'homeParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '2'},
      'awayParticipant': {'participantID': '230',
       'participantName': 'AEK Athens FC',
       'score': '0'}},
     {'matchID': '19412',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '646'},
      'homeParticipant': {'participantID': '685',
       'participantName': 'FC Slovan Liberec',
       'score': '0'},
      'awayParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '0'}},
     {'matchID': '19413',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '199'},
      'homeParticipant': {'participantID': '162',
       'participantName': 'PFC Ludogorets Razgrad',
       'score': '1'},
      'awayParticipant': {'participantID': '152',
       'participantName': 'LASK Linz',
       'score': '3'}},
     {'matchID': '19414',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '702'},
      'homeParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '1'},
      'awayParticipant': {'participantID': '502',
       'participantName': 'Sivasspor',
       'score': '0'}},
     {'matchID': '19415',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '655'},
      'homeParticipant': {'participantID': '682',
       'participantName': 'AC Sparta Praha',
       'score': '0'},
      'awayParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '1'}},
     {'matchID': '19416',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '23'},
      'homeParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '2'},
      'awayParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '0'}},
     {'matchID': '19417',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '3'},
      'awayParticipant': {'participantID': '140',
       'participantName': 'Qarabağ FK',
       'score': '0'}},
     {'matchID': '19423',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2020-12-10',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '206'},
      'homeParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '1'},
      'awayParticipant': {'participantID': '159',
       'participantName': 'Feyenoord Rotterdam',
       'score': '0'}}]},
   {'matchdayID': '2161',
    'matchdayName': '1/16 Final',
    'matchdayPlayoff': '1',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '20259',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '15:00',
      'matchVenue': {'venueID': '178'},
      'homeParticipant': {'participantID': '142',
       'participantName': 'FC Dynamo Kyiv',
       'score': '1'},
      'awayParticipant': {'participantID': '126',
       'participantName': 'Club Brugge KV',
       'score': '1'}},
     {'matchID': '20243',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '203'},
      'homeParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '0'},
      'awayParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '2'}},
     {'matchID': '20244',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '165'},
      'homeParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '2'},
      'awayParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '2'}},
     {'matchID': '20245',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '171'},
      'homeParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '0'},
      'awayParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '0'}},
     {'matchID': '20246',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '206'},
      'homeParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '1'},
      'awayParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '4'}},
     {'matchID': '20260',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '183'},
      'homeParticipant': {'participantID': '148',
       'participantName': 'FC Krasnodar',
       'score': '2'},
      'awayParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '3'}},
     {'matchID': '20261',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '166'},
      'homeParticipant': {'participantID': '136',
       'participantName': 'Olympiacos FC',
       'score': '4'},
      'awayParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '2'}},
     {'matchID': '20262',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '26'},
      'homeParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '0'},
      'awayParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '4'}},
     {'matchID': '20271',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '194'},
      'homeParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '4'},
      'awayParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '3'}},
     {'matchID': '20247',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '504'},
      'homeParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '3'},
      'awayParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '4'}},
     {'matchID': '20248',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '162'},
      'homeParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '1'},
      'awayParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '1'}},
     {'matchID': '20249',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '143'},
      'homeParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '2'},
      'awayParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '0'}},
     {'matchID': '20250',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '700'},
      'homeParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '3'},
      'awayParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '3'}},
     {'matchID': '20263',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '68'},
      'homeParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '1'},
      'awayParticipant': {'participantID': '137',
       'participantName': 'AFC Ajax',
       'score': '2'}},
     {'matchID': '20269',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '702'},
      'homeParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '0'},
      'awayParticipant': {'participantID': '134',
       'participantName': 'FC Shakhtar Donetsk',
       'score': '2'}},
     {'matchID': '20272',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '173'},
      'homeParticipant': {'participantID': '133',
       'participantName': 'FC Red Bull Salzburg',
       'score': '0'},
      'awayParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '2'}},
     {'matchID': '20251',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-24',
      'matchTime': '17:00',
      'matchVenue': {'venueID': '23'},
      'homeParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '4'},
      'awayParticipant': {'participantID': '167',
       'participantName': 'Wolfsberger AC',
       'score': '0'}},
     {'matchID': '20252',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '10'},
      'homeParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '3'},
      'awayParticipant': {'participantID': '131',
       'participantName': 'SL Benfica',
       'score': '2'}},
     {'matchID': '20253',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '50'},
      'homeParticipant': {'participantID': '54',
       'participantName': 'TSG 1899 Hoffenheim',
       'score': '0'},
      'awayParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '2'}},
     {'matchID': '20254',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '121'},
      'homeParticipant': {'participantID': '103',
       'participantName': 'SSC Napoli',
       'score': '2'},
      'awayParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '1'}},
     {'matchID': '20255',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '196'},
      'homeParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '5'},
      'awayParticipant': {'participantID': '501',
       'participantName': 'Royal Antwerp FC',
       'score': '2'}},
     {'matchID': '20264',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '174'},
      'homeParticipant': {'participantID': '137',
       'participantName': 'AFC Ajax',
       'score': '2'},
      'awayParticipant': {'participantID': '69',
       'participantName': 'LOSC Lille',
       'score': '1'}},
     {'matchID': '20270',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '167'},
      'homeParticipant': {'participantID': '134',
       'participantName': 'FC Shakhtar Donetsk',
       'score': '1'},
      'awayParticipant': {'participantID': '720',
       'participantName': 'Maccabi Tel Aviv FC',
       'score': '0'}},
     {'matchID': '20273',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '2'},
      'awayParticipant': {'participantID': '133',
       'participantName': 'FC Red Bull Salzburg',
       'score': '1'}},
     {'matchID': '20256',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '126'},
      'homeParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '1'},
      'awayParticipant': {'participantID': '135',
       'participantName': 'FK Crvena zvezda',
       'score': '1'}},
     {'matchID': '20257',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '128'},
      'homeParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '3'},
      'awayParticipant': {'participantID': '169',
       'participantName': 'SC Braga',
       'score': '1'}},
     {'matchID': '20258',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '1'},
      'homeParticipant': {'participantID': '14',
       'participantName': 'Leicester City',
       'score': '0'},
      'awayParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '2'}},
     {'matchID': '20265',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '163'},
      'homeParticipant': {'participantID': '126',
       'participantName': 'Club Brugge KV',
       'score': '0'},
      'awayParticipant': {'participantID': '142',
       'participantName': 'FC Dynamo Kyiv',
       'score': '1'}},
     {'matchID': '20266',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '168'},
      'homeParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '1'},
      'awayParticipant': {'participantID': '148',
       'participantName': 'FC Krasnodar',
       'score': '0'}},
     {'matchID': '20267',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '12'},
      'homeParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '0'},
      'awayParticipant': {'participantID': '32',
       'participantName': 'Real Sociedad',
       'score': '0'}},
     {'matchID': '20268',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '187'},
      'homeParticipant': {'participantID': '150',
       'participantName': 'PSV Eindhoven',
       'score': '2'},
      'awayParticipant': {'participantID': '136',
       'participantName': 'Olympiacos FC',
       'score': '1'}},
     {'matchID': '20274',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-02-25',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '53'},
      'homeParticipant': {'participantID': '57',
       'participantName': 'Bayer 04 Leverkusen',
       'score': '0'},
      'awayParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '2'}}]},
   {'matchdayID': '2353',
    'matchdayName': '1/8 Final',
    'matchdayPlayoff': '1',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '21745',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '174'},
      'homeParticipant': {'participantID': '137',
       'participantName': 'AFC Ajax',
       'score': '3'},
      'awayParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '0'}},
     {'matchID': '21746',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '178'},
      'homeParticipant': {'participantID': '142',
       'participantName': 'FC Dynamo Kyiv',
       'score': '0'},
      'awayParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '2'}},
     {'matchID': '21747',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '12'},
      'homeParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '1'},
      'awayParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '1'}},
     {'matchID': '21748',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '171'},
      'homeParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '1'},
      'awayParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '1'}},
     {'matchID': '21749',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '128'},
      'homeParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '3'},
      'awayParticipant': {'participantID': '134',
       'participantName': 'FC Shakhtar Donetsk',
       'score': '0'}},
     {'matchID': '21751',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '143'},
      'homeParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '2'},
      'awayParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '0'}},
     {'matchID': '21752',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '166'},
      'homeParticipant': {'participantID': '136',
       'participantName': 'Olympiacos FC',
       'score': '1'},
      'awayParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '3'}},
     {'matchID': '21756',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-11',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '23'},
      'homeParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '2'},
      'awayParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '0'}},
     {'matchID': '21750',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '168'},
      'homeParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '3'},
      'awayParticipant': {'participantID': '2',
       'participantName': 'Tottenham Hotspur FC',
       'score': '0'}},
     {'matchID': '21753',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '10'},
      'homeParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '0'},
      'awayParticipant': {'participantID': '136',
       'participantName': 'Olympiacos FC',
       'score': '1'}},
     {'matchID': '21754',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '700'},
      'homeParticipant': {'participantID': '717',
       'participantName': 'Molde FK',
       'score': '2'},
      'awayParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '1'}},
     {'matchID': '21755',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '17:55',
      'matchVenue': {'venueID': '167'},
      'homeParticipant': {'participantID': '134',
       'participantName': 'FC Shakhtar Donetsk',
       'score': '1'},
      'awayParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '2'}},
     {'matchID': '21757',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '126'},
      'homeParticipant': {'participantID': '96',
       'participantName': 'AC Milan',
       'score': '0'},
      'awayParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '1'}},
     {'matchID': '21758',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '196'},
      'homeParticipant': {'participantID': '160',
       'participantName': 'Rangers FC',
       'score': '0'},
      'awayParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '2'}},
     {'matchID': '21759',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '2'},
      'awayParticipant': {'participantID': '142',
       'participantName': 'FC Dynamo Kyiv',
       'score': '0'}},
     {'matchID': '21760',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-03-18',
      'matchTime': '20:00',
      'matchVenue': {'venueID': '194'},
      'homeParticipant': {'participantID': '158',
       'participantName': 'BSC Young Boys',
       'score': '0'},
      'awayParticipant': {'participantID': '137',
       'participantName': 'AFC Ajax',
       'score': '2'}}]},
   {'matchdayID': '2467',
    'matchdayName': '1/4 Final',
    'matchdayPlayoff': '1',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '22722',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-08',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '174'},
      'homeParticipant': {'participantID': '137',
       'participantName': 'AFC Ajax',
       'score': '1'},
      'awayParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '2'}},
     {'matchID': '22723',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-08',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '10'},
      'homeParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '1'},
      'awayParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '1'}},
     {'matchID': '22724',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-08',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '168'},
      'homeParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '0'},
      'awayParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '1'}},
     {'matchID': '22725',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-08',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '143'},
      'homeParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '0'},
      'awayParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '2'}},
     {'matchID': '22726',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-15',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '128'},
      'homeParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '1'},
      'awayParticipant': {'participantID': '137',
       'participantName': 'AFC Ajax',
       'score': '1'}},
     {'matchID': '22727',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-15',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '12'},
      'homeParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '2'},
      'awayParticipant': {'participantID': '116',
       'participantName': 'Granada CF',
       'score': '0'}},
     {'matchID': '22728',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-15',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '171'},
      'homeParticipant': {'participantID': '127',
       'participantName': 'SK Slavia Praha',
       'score': '0'},
      'awayParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '4'}},
     {'matchID': '22729',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-15',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '2'},
      'awayParticipant': {'participantID': '130',
       'participantName': 'GNK Dinamo Zagreb',
       'score': '1'}}]},
   {'matchdayID': '2552',
    'matchdayName': '1/2 Final',
    'matchdayPlayoff': '1',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '23940',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-29',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '12'},
      'homeParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '6'},
      'awayParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '2'}},
     {'matchID': '23941',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-04-29',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '2'},
      'awayParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '1'}},
     {'matchID': '23942',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-05-06',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '10'},
      'homeParticipant': {'participantID': '9',
       'participantName': 'Arsenal FC',
       'score': '0'},
      'awayParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '0'}},
     {'matchID': '23943',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-05-06',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '128'},
      'homeParticipant': {'participantID': '91',
       'participantName': 'AS Roma',
       'score': '3'},
      'awayParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '2'}}]},
   {'matchdayID': '2605',
    'matchdayName': 'Final',
    'matchdayPlayoff': '1',
    'matchdayType': '0',
    'matchdayStart': None,
    'matchdayEnd': None,
    'matches': [{'matchID': '24369',
      'matchStatus': {'statusID': '1'},
      'matchDate': '2021-05-26',
      'matchTime': '19:00',
      'matchVenue': {'venueID': '32'},
      'homeParticipant': {'participantID': '38',
       'participantName': 'Villarreal CF',
       'score': '1'},
      'awayParticipant': {'participantID': '7',
       'participantName': 'Manchester United',
       'score': '1'}}]}]}}
