# Generated by Django 3.2.3 on 2021-05-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='User Name')),
                ('gid_8222', models.CharField(max_length=6, verbose_name='Turkey - Italy')),
                ('gid_8198', models.CharField(max_length=6, verbose_name='Wales - Switzerland')),
                ('gid_8199', models.CharField(max_length=6, verbose_name='Denmark - Finland')),
                ('gid_8200', models.CharField(max_length=6, verbose_name='Belgium - Russia')),
                ('gid_8201', models.CharField(max_length=6, verbose_name='England - Croatia')),
                ('gid_19950', models.CharField(max_length=6, verbose_name='Austria - North Macedonia')),
                ('gid_8202', models.CharField(max_length=6, verbose_name='Netherlands - Ukraine')),
                ('gid_19951', models.CharField(max_length=6, verbose_name='Scotland - Czech Republic')),
                ('gid_19952', models.CharField(max_length=6, verbose_name='Poland - Slovakia')),
                ('gid_8203', models.CharField(max_length=6, verbose_name='Spain - Sweden')),
                ('gid_19949', models.CharField(max_length=6, verbose_name='Hungary - Portugal')),
                ('gid_8204', models.CharField(max_length=6, verbose_name='France - Germany')),
                ('gid_8205', models.CharField(max_length=6, verbose_name='Finland - Russia')),
                ('gid_8206', models.CharField(max_length=6, verbose_name='Turkey - Wales')),
                ('gid_8207', models.CharField(max_length=6, verbose_name='Italy - Switzerland')),
                ('gid_19953', models.CharField(max_length=6, verbose_name='Ukraine - North Macedonia')),
                ('gid_8208', models.CharField(max_length=6, verbose_name='Denmark - Belgium')),
                ('gid_8209', models.CharField(max_length=6, verbose_name='Netherlands - Austria')),
                ('gid_19954', models.CharField(max_length=6, verbose_name='Sweden - Slovakia')),
                ('gid_8210', models.CharField(max_length=6, verbose_name='Croatia - Czech Republic')),
                ('gid_19955', models.CharField(max_length=6, verbose_name='England - Scotland')),
                ('gid_19956', models.CharField(max_length=6, verbose_name='Hungary - France')),
                ('gid_8211', models.CharField(max_length=6, verbose_name='Portugal - Germany')),
                ('gid_8212', models.CharField(max_length=6, verbose_name='Spain - Poland')),
                ('gid_8213', models.CharField(max_length=6, verbose_name='Italy - Wales')),
                ('gid_8214', models.CharField(max_length=6, verbose_name='Switzerland - Turkey')),
                ('gid_8215', models.CharField(max_length=6, verbose_name='Ukraine - Austria')),
                ('gid_19957', models.CharField(max_length=6, verbose_name='North Macedonia - Netherlands')),
                ('gid_8216', models.CharField(max_length=6, verbose_name='Finland - Belgium')),
                ('gid_8217', models.CharField(max_length=6, verbose_name='Russia - Denmark')),
                ('gid_8218', models.CharField(max_length=6, verbose_name='Czech Republic - England')),
                ('gid_19958', models.CharField(max_length=6, verbose_name='Croatia - Scotland')),
                ('gid_8219', models.CharField(max_length=6, verbose_name='Sweden - Poland')),
                ('gid_19959', models.CharField(max_length=6, verbose_name='Slovakia - Spain')),
                ('gid_8220', models.CharField(max_length=6, verbose_name='Portugal - France')),
                ('gid_19960', models.CharField(max_length=6, verbose_name='Germany - Hungary')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=20, verbose_name='League Name')),
                ('league_owner', models.CharField(max_length=20, verbose_name='League Manager')),
                ('league_owner_email', models.EmailField(max_length=254, verbose_name='League Manager Email')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
