# Generated by Django 3.2.3 on 2021-05-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210531_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
