# Generated by Django 3.2.3 on 2021-06-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_alter_leagueuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='CleanPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_label', models.CharField(max_length=100, verbose_name='Match')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('predicted_score', models.CharField(max_length=100, verbose_name='Predicted Score')),
                ('real_score', models.CharField(max_length=100, verbose_name='Real Score')),
                ('game_status', models.CharField(max_length=100, verbose_name='Game Status')),
                ('date', models.DateField(max_length=100, verbose_name='Date')),
                ('hour', models.TimeField(max_length=100, verbose_name='Hour')),
                ('pred_score_home', models.IntegerField(verbose_name='Predicted Score Home')),
                ('pred_score_away', models.IntegerField(verbose_name='Predicted Score Away')),
                ('real_score_home', models.IntegerField(verbose_name='Real Score Home')),
                ('real_score_away', models.IntegerField(verbose_name='Real Score Away')),
                ('league_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.league', to_field='league_name')),
                ('user_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
