# Generated by Django 3.2.3 on 2021-06-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210601_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanpredictions',
            old_name='league_name_id',
            new_name='league_name',
        ),
        migrations.RenameField(
            model_name='cleanpredictions',
            old_name='user_name_id',
            new_name='user_name',
        ),
    ]
