# Generated by Django 3.2.3 on 2021-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210601_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanpredictions',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cleanpredictions',
            name='user_full_name',
            field=models.CharField(default='Dor Polo', max_length=100, verbose_name='Match'),
            preserve_default=False,
        ),
    ]
