# Generated by Django 3.2.3 on 2021-06-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210602_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_owner_email',
        ),
    ]
