# Generated by Django 3.2.3 on 2021-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_league_league_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueuser',
            name='nick_name',
            field=models.CharField(default='Polo', max_length=20, verbose_name='Nick Name'),
            preserve_default=False,
        ),
    ]
