# Generated by Django 3.2.3 on 2021-06-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_leagueuser_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
