# Generated by Django 3.2.3 on 2021-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_leagueuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
