# Generated by Django 3.2.3 on 2021-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueuser',
            name='image',
        ),
        migrations.AddField(
            model_name='leagueuser',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
