# Generated by Django 3.2.3 on 2021-06-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_leaguemember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueUser',
        ),
    ]
