# Generated by Django 3.2.3 on 2021-06-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user',
            new_name='user_name',
        ),
    ]
