# Generated by Django 3.2.3 on 2021-06-06 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_user_userimage_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='leaguemember',
            name='header_image',
        ),
        migrations.AddField(
            model_name='userimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
