# Generated by Django 3.2.3 on 2021-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210606_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='User Image'),
        ),
    ]
